# Directories arguments
data_dir: "../../volcap/SyntheticData/blender/outputs" #"synthetic_seq"
exp_dir:  "unet_depthnet_4_chan"
out_dir:  "unet_depthnet_4_chan"

# Data arguments
# image dimensions are reduced to enable run on my pc
img_height:   370 #740
img_width:    640 #1280
num_channels: 4
num_classes:  9
r_labels: True

# Train arguments
num_epochs: 200
batch_size: 10
train_data_len: 2000
shuffle: True
dropout_keep_prob: 0.95
data_mode: "experiment"
save_every: 10
test_every: 10
max_to_keep: 2
weighted_loss: False
random_cropping: False
freeze_encoder: False

# Models arguments
learning_rate:   0.0001
weight_decay: 0.0005
bias : 0.0
batchnorm_enabled: True
#pretrained_path: "pretrained_weights/mobilenet_v1.pkl"

# Misc arguments
verbose: False

